### ISSUE TITLE
What to do with BaseURI in the RDF4J parser?

### ISSUE THREAD

**Issue by Flurb** [com-pas/compas-cim-mapping#17]
We currently parse a RDF file as follows:

`Model model = Rio.parse(new FileInputStream(file), "http://example.uri", RDFFormat.RDFXML);`

It's not working unless we add a (random) baseURI (like http://example.uri for example).
Why is this? And how can we make this a bit more clean?

**Comment by dlabordus** [comment]
Currenlty we decided to use PowSyBl (CgmesModel part) to read the CIM File. 
So this issue is not applicable anymore.
