### ISSUE TITLE
Map CIM class 'LoadBreakSwitch' to IEC 61850 SCL equivalent

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-cim-mapping#31]
As an engineer
I want to map the IEC CIM 'LoadBreakSwitch' class to the IEC 61850 equivalent
So I can generate 61850 single line diagrams without manual editing

Background:
Mapping can be based on IEC/TS 62361-102

**Comment by dlabordus** [comment]
In the CGMES Model of PowSyBl this class is handled the same way as a Breaker, Disconnector and more. So the mapping is also the same for these classes.
