### ISSUE TITLE
Add SmallRye JWT Security to project

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-cim-mapping#60]
As a security officer 
I want user to be authenticated 
So that only known users can use the CIM Mapping Service.

Background:
We only want logged in users to be able to use the CIM Mapping Service.
Also the username is set on the History Record in the create SCL.

**Comment by nicorikken** [comment]
@dlabordus on the Alliander OpenShift cluster we only need JWT validation, as all OIDC flow is handled centrally including session state management. Quarkus docs: https://quarkus.io/guides/security-jwt Potential issue is that `quarkus.oidc.enabled` is set at build-time, so it might need different compilation for Alliander compared to a more generic solution for other use-cases where it includes OIDC.
