### ISSUE TITLE
Fix UniqueID bug in Powertransformer CIM to IEC61850 transformation

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-cim-mapping#89]
When I test a generic CGMES file and convert it 61850, and error occurs in the validation.

[Example CGMES Grid.zip](https://github.com/com-pas/compas-cim-mapping/files/7121420/Example.CGMES.Grid.zip)

![image](https://user-images.githubusercontent.com/7427358/132343303-a6d52fba-ceef-4ef8-bc50-6c9067a423b2.png)

**Comment by dlabordus** [comment]
The name is from the PowerTransformer in CGMES Model, but in the RDF File the name of the PowerTransformerEnd is also not unique.

so to fix the problem I saw the field EndNumber in the RDF Mapping. Proposal is to combine the Name and EndNumer (with underscore between them)
